export default data = [
  {
    name: "Romeo Moodley",
    jobTitle: "Accountant",
    age: 24,
    experience: "4 Years",
    highestEducation: "Degree",
    profilephoto: "someURLhere",
    currentSector: "Accounting",
    prevJobTitles: ["Data analyst intern Sep 2020 - present"],
    skills: ["Time management", "Systems analysis", "Critical thinking"],
    gender: "Male",
    ethnicity: "Indian",
    nationality: "South African",
    disabled: "No",
    languages: ["English"],
    location: "Johannesburg",
    summary:
      "I am an outgoing person who is friendly, I like making new friends who have ideas and l am a critical thinker and a great problems solver. Playing football and football has been part of me ever since I was a young boy. Helping people in the communities is part of my activities, contributing in the communities where people are in need of my services.I enjoy voluntary work for individuals and companies as it allows me togrow and meet new friends who have same interests as me.",
  },
  {
    name: "Mike Tyson",
    jobTitle: "Software Engineer",
    age: 26,
    experience: "2 Years",
    highestEducation: "Degree",
    profilephoto: "someURLhere",
    currentSector: "Information Technology",
    prevJobTitles: [
      "Software developer intern Jan 2012 - Jul 2012",
      "Barista Feb 2012 - Aug 2014",
    ],
    skills: ["Time management", "HTML", "CSS", "Java", "Version Control"],
    gender: "Male",
    ethnicity: "African",
    nationality: "South African",
    disabled: "No",
    languages: ["English", "Afrikaans", "Zulu"],
    location: "Johannesburg",
    summary:
      "I am an outgoing person who is friendly, I like making new friends who have ideas and l am a critical thinker and a great problems solver. Playing football and football has been part of me ever since I was a young boy. Helping people in the communities is part of my activities, contributing in the communities where people are in need of my services.I enjoy voluntary work for individuals and companies as it allows me togrow and meet new friends who have same interests as me.",
  },
  {
    name: "Cynthia Rothrock",
    jobTitle: "Risk Manager",
    age: 30,
    experience: "7 Years",
    highestEducation: "Degree",
    profilephoto: "someURLhere",
    currentSector: "Risk and Public Relations",
    prevJobTitles: [
      "Waiter Jan 2010 - May 2012",
      "Au pair Jun 2012 - Aug 2013",
    ],
    skills: [
      "Time management",
      "Work well under pressure",
      "Analytical skills",
    ],
    gender: "Female",
    ethnicity: "White",
    nationality: "South African",
    disabled: "No",
    languages: ["English", "Afrikaans"],
    location: "Johannesburg",
    summary:
      "I am an outgoing person who is friendly, I like making new friends who have ideas and l am a critical thinker and a great problems solver. Playing football and football has been part of me ever since I was a young boy. Helping people in the communities is part of my activities, contributing in the communities where people are in need of my services.I enjoy voluntary work for individuals and companies as it allows me togrow and meet new friends who have same interests as me.",
  },
];
